# Generated by Django 2.2.5 on 2022-01-25 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
