# Generated by Django 2.2.5 on 2022-01-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeboard', '0002_auto_20220127_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='post',
            name='top_fixed',
        ),
    ]
