# Generated by Django 2.2.5 on 2022-01-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeboard', '0003_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mainphoto',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
