# Generated by Django 2.2.5 on 2022-01-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeboard', '0004_auto_20220124_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to='pb/images'),
        ),
    ]
