# Generated by Django 2.2.5 on 2022-01-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeboard', '0005_post_mainphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mainphoto',
        ),
    ]
