# Generated by Django 2.2.5 on 2022-01-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapquiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('play_time', models.IntegerField(default=0, null=True)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
    ]
