# Generated by Django 2.2.5 on 2022-01-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapquiz', '0002_quizlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
    ]
