# Generated by Django 2.2.5 on 2022-01-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapquiz', '0003_auto_20220125_2111'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='place',
            table=None,
        ),
    ]
