# Generated by Django 2.2.5 on 2022-01-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapquiz', '0005_auto_20220126_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizlog',
            old_name='user',
            new_name='username',
        ),
    ]
