# Generated by Django 2.2.5 on 2022-01-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapquiz', '0006_auto_20220126_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizlog',
            old_name='username',
            new_name='user',
        ),
    ]
