# Generated by Django 2.2.5 on 2022-01-26 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapquiz', '0007_auto_20220126_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
