# Generated by Django 2.2.5 on 2022-01-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapquiz', '0008_auto_20220126_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='explain',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
