# Generated by Django 2.2.5 on 2022-01-27 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapquiz', '0009_place_explain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
