# Generated by Django 2.2.5 on 2022-01-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user_point',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
